/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface PdSideDrawer {
    'name': string;
  }
  interface PdSideDrawerAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'PdSideDrawer': Components.PdSideDrawer;
  }

  interface StencilIntrinsicElements {
    'pd-side-drawer': Components.PdSideDrawerAttributes;
  }


  interface HTMLPdSideDrawerElement extends Components.PdSideDrawer, HTMLStencilElement {}
  var HTMLPdSideDrawerElement: {
    prototype: HTMLPdSideDrawerElement;
    new (): HTMLPdSideDrawerElement;
  };

  interface HTMLElementTagNameMap {
    'pd-side-drawer': HTMLPdSideDrawerElement
  }

  interface ElementTagNameMap {
    'pd-side-drawer': HTMLPdSideDrawerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
