/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@ionic/core';
import 'ionicons';


export namespace Components {

  interface AppRoot {}
  interface AppRootAttributes extends StencilHTMLAttributes {}

  interface AppHeader {
    'delete': boolean;
    'isHome': boolean;
    'pageTitle': string;
  }
  interface AppHeaderAttributes extends StencilHTMLAttributes {
    'delete'?: boolean;
    'isHome'?: boolean;
    'onDeleteClick'?: (event: CustomEvent) => void;
    'pageTitle'?: string;
  }

  interface AppRecipe {
    'id': string;
    'image': string;
    'ingredients': string[];
    'recipeTitle': string;
  }
  interface AppRecipeAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'image'?: string;
    'ingredients'?: string[];
    'recipeTitle'?: string;
  }

  interface AppHome {}
  interface AppHomeAttributes extends StencilHTMLAttributes {}

  interface AppProfile {
    'name': string;
  }
  interface AppProfileAttributes extends StencilHTMLAttributes {
    'name'?: string;
  }

  interface AppRecipeDetail {}
  interface AppRecipeDetailAttributes extends StencilHTMLAttributes {}

  interface AppRecipes {}
  interface AppRecipesAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppRoot': Components.AppRoot;
    'AppHeader': Components.AppHeader;
    'AppRecipe': Components.AppRecipe;
    'AppHome': Components.AppHome;
    'AppProfile': Components.AppProfile;
    'AppRecipeDetail': Components.AppRecipeDetail;
    'AppRecipes': Components.AppRecipes;
  }

  interface StencilIntrinsicElements {
    'app-root': Components.AppRootAttributes;
    'app-header': Components.AppHeaderAttributes;
    'app-recipe': Components.AppRecipeAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-profile': Components.AppProfileAttributes;
    'app-recipe-detail': Components.AppRecipeDetailAttributes;
    'app-recipes': Components.AppRecipesAttributes;
  }


  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {}
  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new (): HTMLAppRootElement;
  };

  interface HTMLAppHeaderElement extends Components.AppHeader, HTMLStencilElement {}
  var HTMLAppHeaderElement: {
    prototype: HTMLAppHeaderElement;
    new (): HTMLAppHeaderElement;
  };

  interface HTMLAppRecipeElement extends Components.AppRecipe, HTMLStencilElement {}
  var HTMLAppRecipeElement: {
    prototype: HTMLAppRecipeElement;
    new (): HTMLAppRecipeElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {}
  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new (): HTMLAppProfileElement;
  };

  interface HTMLAppRecipeDetailElement extends Components.AppRecipeDetail, HTMLStencilElement {}
  var HTMLAppRecipeDetailElement: {
    prototype: HTMLAppRecipeDetailElement;
    new (): HTMLAppRecipeDetailElement;
  };

  interface HTMLAppRecipesElement extends Components.AppRecipes, HTMLStencilElement {}
  var HTMLAppRecipesElement: {
    prototype: HTMLAppRecipesElement;
    new (): HTMLAppRecipesElement;
  };

  interface HTMLElementTagNameMap {
    'app-root': HTMLAppRootElement
    'app-header': HTMLAppHeaderElement
    'app-recipe': HTMLAppRecipeElement
    'app-home': HTMLAppHomeElement
    'app-profile': HTMLAppProfileElement
    'app-recipe-detail': HTMLAppRecipeDetailElement
    'app-recipes': HTMLAppRecipesElement
  }

  interface ElementTagNameMap {
    'app-root': HTMLAppRootElement;
    'app-header': HTMLAppHeaderElement;
    'app-recipe': HTMLAppRecipeElement;
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-recipe-detail': HTMLAppRecipeDetailElement;
    'app-recipes': HTMLAppRecipesElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
